# Welcome to Jekyll!
# Basic Site Settings
locale                   : "en-US"
title                    : "Heng (Mac) ZHANG"
title_separator          : "-"
name                     : &name "Heng Zhang"
description              : &description "MScFin at CUHK; BEcon at NKU"
url                      : https://academicpages.github.io
baseurl                  : ""
repository               : "academicpages/academicpages.github.io"

# Site Author
author:
  avatar           : "MyPhoto.jpg"
  name             : "Heng Zhang"
  pronouns         : "he/him"
  bio              : "MScFin (CUHK); BEcon (NKU)"
  location         : "HKSAR, China"
  employer         : "The Chinese University of Hong Kong"
  email            : "kmmacz@outlook.com"

# Publication Category
publication_category:
  manuscripts:
    title: "Papers"

# CV Category
publication_category:
  manuscripts:
    title: "CV"

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

